# ==============================================================================
# Merged Lakeflow Source: tsuga_logs
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import Decimal
from typing import (
    Any,
    Callable,
    Iterable,
    Iterator,
    Mapping,
    Sequence,
)
import json
import time

from .client import (
    NormalizedLogRecord,
    TsugaPublicLogsClient,
    build_resume_offset,
    filter_records_from_offset,
    iter_windows,
)
from .incremental_read import collect_windowed_records
from concurrent.futures import ThreadPoolExecutor
from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
from threading import Lock
import base64
import hashlib
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/tsuga_logs/client.py
    ########################################################

    JsonDict = dict[str, Any]
    SearchFn = Callable[[Mapping[str, Any]], JsonDict]
    MAX_PUBLIC_LOGS_PER_CALL = 1000
    DEFAULT_RETRY_MAX_ATTEMPTS = 20
    DEFAULT_RETRY_BACKOFF_SECONDS = 1.0
    DEFAULT_MAX_RETRY_BACKOFF_SECONDS = 60.0
    DEFAULT_MIN_REQUEST_INTERVAL_SECONDS = 1.0


    def _to_iso8601_utc(timestamp_ms: int) -> str:
        return datetime.fromtimestamp(timestamp_ms / 1000, tz=timezone.utc).isoformat()


    def _parse_retry_after_seconds(value: str | None) -> float | None:
        if value is None:
            return None
        try:
            parsed = float(value)
        except (TypeError, ValueError):
            return None
        if parsed < 0:
            return None
        return parsed


    def _extract_error_message(response: requests.Response) -> str | None:
        try:
            body = response.json()
        except ValueError:
            return None
        if not isinstance(body, dict):
            return None
        error = body.get("error")
        if isinstance(error, dict) and error.get("message") is not None:
            return str(error["message"])
        if body.get("message") is not None:
            return str(body["message"])
        return None


    def _extract_service_name(log: Mapping[str, Any]) -> str | None:
        context = log.get("context", {})
        if isinstance(context, dict):
            service = context.get("service")
            if isinstance(service, dict):
                name = service.get("name")
                if name is not None:
                    return str(name)
            if context.get("service_name") is not None:
                return str(context["service_name"])
        if log.get("service_name") is not None:
            return str(log["service_name"])
        return None


    def _extract_team(log: Mapping[str, Any]) -> str | None:
        context = log.get("context", {})
        if isinstance(context, dict) and context.get("team") is not None:
            return str(context["team"])
        return None


    def _extract_env(log: Mapping[str, Any]) -> str | None:
        context = log.get("context", {})
        if isinstance(context, dict) and context.get("env") is not None:
            return str(context["env"])
        return None


    @dataclass(frozen=True)
    class NormalizedLogRecord:
        event_time_ms: int
        event_time_sec: int
        level: str | None
        message: str | None
        service_name: str | None
        team: str | None
        env: str | None
        raw_json: str
        extracted_at: str
        fingerprint: str

        def to_row(self) -> dict[str, Any]:
            return {
                "event_time": _to_iso8601_utc(self.event_time_ms),
                "level": self.level,
                "message": self.message,
                "service_name": self.service_name,
                "team": self.team,
                "env": self.env,
                "raw_json": self.raw_json,
                "extracted_at": self.extracted_at,
            }


    def normalize_log(log: Mapping[str, Any], extracted_at: str) -> NormalizedLogRecord:
        raw_json = json.dumps(log, sort_keys=True, default=str, separators=(",", ":"))
        timestamp_ms = int(log["timestamp"])
        return NormalizedLogRecord(
            event_time_ms=timestamp_ms,
            event_time_sec=timestamp_ms // 1000,
            level=str(log["level"]) if log.get("level") is not None else None,
            message=str(log["message"]) if log.get("message") is not None else None,
            service_name=_extract_service_name(log),
            team=_extract_team(log),
            env=_extract_env(log),
            raw_json=raw_json,
            extracted_at=extracted_at,
            fingerprint=hashlib.sha256(raw_json.encode("utf-8")).hexdigest(),
        )


    def iter_windows(
        start_seconds: int,
        window_seconds: int,
        max_concurrency: int,
        end_exclusive_seconds: int,
    ) -> list[tuple[int, int]]:
        if window_seconds <= 0:
            raise ValueError("window_seconds must be > 0")
        if max_concurrency <= 0:
            raise ValueError("max_concurrency must be > 0")

        windows: list[tuple[int, int]] = []
        cursor = start_seconds
        for _ in range(max_concurrency):
            if cursor >= end_exclusive_seconds:
                break
            end_cursor = min(cursor + window_seconds, end_exclusive_seconds)
            windows.append((cursor, end_cursor))
            cursor = end_cursor
        return windows


    def filter_records_from_offset(
        records: Iterable[NormalizedLogRecord],
        cursor_seconds: int,
        seen_fingerprints_at_cursor: set[str],
    ) -> list[NormalizedLogRecord]:
        filtered: list[NormalizedLogRecord] = []
        for record in records:
            if record.event_time_sec < cursor_seconds:
                continue
            if (
                record.event_time_sec == cursor_seconds
                and record.fingerprint in seen_fingerprints_at_cursor
            ):
                continue
            filtered.append(record)
        return filtered


    def build_resume_offset(records: list[NormalizedLogRecord]) -> dict[str, Any]:
        if not records:
            raise ValueError("build_resume_offset requires at least one record")
        last_second = records[-1].event_time_sec
        seen = sorted(
            {record.fingerprint for record in records if record.event_time_sec == last_second}
        )
        return {
            "cursor_seconds": last_second,
            "seen_fingerprints_at_cursor": seen,
        }


    class TsugaPublicLogsClient:
        """Thin wrapper over Tsuga's public logs search API.

        The public API exposes `maxResults` but caps it at 1000 and does not expose
        a cursor token. To exhaust a time range, this client recursively splits the
        range into smaller half-open windows until each call returns fewer than the
        per-call cap.
        """

        def __init__(
            self,
            base_url: str,
            operation_api_key: str,
            *,
            request_timeout_seconds: float = 60.0,
            retry_max_attempts: int = DEFAULT_RETRY_MAX_ATTEMPTS,
            retry_backoff_seconds: float = DEFAULT_RETRY_BACKOFF_SECONDS,
            max_retry_backoff_seconds: float = DEFAULT_MAX_RETRY_BACKOFF_SECONDS,
            min_request_interval_seconds: float = DEFAULT_MIN_REQUEST_INTERVAL_SECONDS,
            search_fn: SearchFn | None = None,
        ) -> None:
            self.base_url = base_url.rstrip("/")
            self.operation_api_key = operation_api_key
            self.request_timeout_seconds = request_timeout_seconds
            self.retry_max_attempts = max(1, retry_max_attempts)
            self.retry_backoff_seconds = max(0.0, retry_backoff_seconds)
            self.max_retry_backoff_seconds = max(0.0, max_retry_backoff_seconds)
            self.min_request_interval_seconds = max(0.0, min_request_interval_seconds)
            self._search_fn = search_fn
            self._request_lock = Lock()
            self._next_request_monotonic = 0.0

        def _search(self, params: Mapping[str, Any]) -> JsonDict:
            if self._search_fn is not None:
                return self._search_fn(params)

            attempt = 0
            while True:
                try:
                    self._apply_request_rate_limit()
                    response = requests.get(
                        f"{self.base_url}/v1/logs/search",
                        headers={
                            "Accept": "application/json",
                            "Authorization": f"Bearer {self.operation_api_key}",
                        },
                        params=params,
                        timeout=self.request_timeout_seconds,
                    )
                except requests.RequestException:
                    if not self._should_retry(attempt):
                        raise
                    time.sleep(self._retry_delay_seconds(None, attempt))
                    attempt += 1
                    continue

                if self._should_retry(attempt) and self._is_retryable_status(response.status_code):
                    time.sleep(self._retry_delay_seconds(response, attempt))
                    attempt += 1
                    continue

                try:
                    response.raise_for_status()
                except requests.HTTPError as error:
                    detail = _extract_error_message(response)
                    if detail is not None:
                        raise requests.HTTPError(
                            f"{error}: {detail}", response=response
                        ) from None
                    raise
                return response.json()

        @staticmethod
        def _is_retryable_status(status_code: int) -> bool:
            return status_code == 429 or status_code == 408 or 500 <= status_code < 600

        def _should_retry(self, attempt: int) -> bool:
            return attempt < self.retry_max_attempts - 1

        def _retry_delay_seconds(self, response: requests.Response | None, attempt: int) -> float:
            if response is not None:
                retry_after = _parse_retry_after_seconds(response.headers.get("Retry-After"))
                if retry_after is not None:
                    return min(retry_after, self.max_retry_backoff_seconds)

            delay = self.retry_backoff_seconds * (2**attempt)
            return min(delay, self.max_retry_backoff_seconds)

        def _apply_request_rate_limit(self) -> None:
            if self.min_request_interval_seconds <= 0:
                return

            with self._request_lock:
                now = time.monotonic()
                wait_seconds = self._next_request_monotonic - now
                if wait_seconds > 0:
                    time.sleep(wait_seconds)
                self._next_request_monotonic = time.monotonic() + self.min_request_interval_seconds

        @staticmethod
        def _extract_logs(body: JsonDict) -> list[JsonDict]:
            if not isinstance(body, dict):
                raise RuntimeError("Unexpected Tsuga logs response payload")

            if "logs" in body:
                logs = body["logs"]
            else:
                data = body.get("data")
                if not isinstance(data, dict) or "logs" not in data:
                    raise RuntimeError("Unexpected Tsuga logs response payload")
                logs = data["logs"]

            if not isinstance(logs, list):
                raise RuntimeError("Unexpected Tsuga logs response payload")
            return logs

        def fetch_window(
            self,
            *,
            from_seconds: int,
            to_exclusive_seconds: int,
            query: str,
            page_size: int,
            extracted_at: str,
            cluster_id: str | None = None,
            allow_truncated_seconds: bool = False,
        ) -> list[NormalizedLogRecord]:
            if to_exclusive_seconds <= from_seconds:
                return []

            effective_page_size = min(page_size, MAX_PUBLIC_LOGS_PER_CALL)
            collected = self._fetch_range_recursive(
                from_seconds=from_seconds,
                to_exclusive_seconds=to_exclusive_seconds,
                query=query,
                page_size=effective_page_size,
                extracted_at=extracted_at,
                cluster_id=cluster_id,
                allow_truncated_seconds=allow_truncated_seconds,
            )

            collected.sort(key=lambda record: (record.event_time_ms, record.fingerprint))
            return collected

        def _fetch_range_recursive(
            self,
            *,
            from_seconds: int,
            to_exclusive_seconds: int,
            query: str,
            page_size: int,
            extracted_at: str,
            cluster_id: str | None,
            allow_truncated_seconds: bool,
        ) -> list[NormalizedLogRecord]:
            params: dict[str, Any] = {
                "from": from_seconds,
                "to": to_exclusive_seconds - 1,
                "query": query,
                "maxResults": page_size,
            }
            if cluster_id is not None:
                params["clusterId"] = cluster_id
            body = self._search(params)
            logs = self._extract_logs(body)

            if len(logs) < page_size:
                return [normalize_log(log, extracted_at) for log in logs]

            if to_exclusive_seconds - from_seconds <= 1:
                if allow_truncated_seconds:
                    return [normalize_log(log, extracted_at) for log in logs]
                raise RuntimeError(
                    "Tsuga public logs API saturated a 1-second window at the per-call "
                    f"limit ({page_size}). This query cannot be fully paginated with the "
                    "public endpoint. Narrow the query, reduce per-second volume, or set "
                    "'allow_truncated_seconds' to accept partial data for such seconds."
                )

            midpoint = from_seconds + max(1, (to_exclusive_seconds - from_seconds) // 2)
            if midpoint >= to_exclusive_seconds:
                midpoint = to_exclusive_seconds - 1

            left = self._fetch_range_recursive(
                from_seconds=from_seconds,
                to_exclusive_seconds=midpoint,
                query=query,
                page_size=page_size,
                extracted_at=extracted_at,
                cluster_id=cluster_id,
                allow_truncated_seconds=allow_truncated_seconds,
            )
            right = self._fetch_range_recursive(
                from_seconds=midpoint,
                to_exclusive_seconds=to_exclusive_seconds,
                query=query,
                page_size=page_size,
                extracted_at=extracted_at,
                cluster_id=cluster_id,
                allow_truncated_seconds=allow_truncated_seconds,
            )
            return left + right


    ########################################################
    # src/databricks/labs/community_connector/sources/tsuga_logs/incremental_read.py
    ########################################################

    FetchWindowsFn = Callable[
        [list[tuple[int, int]]],
        list[list[NormalizedLogRecord]],
    ]


    @dataclass(frozen=True)
    class WindowedReadResult:
        records: list[NormalizedLogRecord]
        next_cursor_seconds: int
        resume_offset: dict[str, Any] | None


    def collect_windowed_records(
        *,
        start_seconds: int,
        end_exclusive_seconds: int,
        window_seconds: int,
        max_concurrency: int,
        max_events: int | None,
        seen_fingerprints_at_cursor: set[str],
        fetch_windows: FetchWindowsFn,
    ) -> WindowedReadResult:
        collected: list[NormalizedLogRecord] = []
        remaining = max_events
        next_start_seconds = start_seconds
        first_batch = True

        while next_start_seconds < end_exclusive_seconds:
            if remaining is not None and remaining <= 0:
                break

            windows = iter_windows(
                start_seconds=next_start_seconds,
                window_seconds=window_seconds,
                max_concurrency=max_concurrency,
                end_exclusive_seconds=end_exclusive_seconds,
            )
            if not windows:
                break

            fetched_by_window = fetch_windows(windows)
            for index, records in enumerate(fetched_by_window):
                filtered = filter_records_from_offset(
                    records,
                    cursor_seconds=start_seconds,
                    seen_fingerprints_at_cursor=(
                        seen_fingerprints_at_cursor if first_batch and index == 0 else set()
                    ),
                )

                if remaining is not None and len(filtered) > remaining:
                    collected.extend(filtered[:remaining])
                    return WindowedReadResult(
                        records=collected,
                        next_cursor_seconds=collected[-1].event_time_sec,
                        resume_offset=build_resume_offset(collected),
                    )

                collected.extend(filtered)
                if remaining is not None:
                    remaining -= len(filtered)

            first_batch = False
            next_start_seconds = windows[-1][1]

        return WindowedReadResult(
            records=collected,
            next_cursor_seconds=next_start_seconds,
            resume_offset=None,
        )


    ########################################################
    # src/databricks/labs/community_connector/sources/tsuga_logs/tsuga_logs.py
    ########################################################

    @dataclass(frozen=True)
    class TableOptions:
        query: str
        cluster_id: str | None
        initial_lookback_seconds: int
        incremental_overlap_seconds: int
        window_seconds: int
        page_size: int
        max_concurrency: int
        max_events_per_sync: int | None
        request_timeout_seconds: int
        allow_truncated_seconds: bool


    class TsugaLogsLakeflowConnect(LakeflowConnect):
        """Logs-only Tsuga connector using the public operation-key API."""

        DEFAULT_BASE_URL = "https://api.tsuga.com"
        DEFAULT_INITIAL_LOOKBACK_SECONDS = 3600
        DEFAULT_INCREMENTAL_OVERLAP_SECONDS = 60
        DEFAULT_WINDOW_SECONDS = 300
        DEFAULT_PAGE_SIZE = 1000
        DEFAULT_MAX_CONCURRENCY = 1
        DEFAULT_REQUEST_TIMEOUT_SECONDS = 60

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            operation_api_key = options.get("operation_api_key")
            if not operation_api_key:
                raise ValueError("Missing required connection parameter 'operation_api_key'")

            self._base_url = options.get("base_url", self.DEFAULT_BASE_URL).rstrip("/")
            self._operation_api_key = operation_api_key
            # Connection-level defaults; table options override per table. Named
            # default_* so they can never key-collide with per-table options —
            # the framework forbids a pipeline option whose key exists on the
            # connection. Legacy unprefixed names still honored.
            self._default_query = options.get("default_query") or options.get("query") or None
            self._default_cluster_id = (
                options.get("default_cluster_id") or options.get("cluster_id") or None
            )
            self._init_end_exclusive_seconds = int(datetime.now(timezone.utc).timestamp()) + 1
            self._extracted_at = datetime.now(timezone.utc).isoformat()
            self._default_request_timeout_seconds = self._parse_positive_int(
                options.get("request_timeout_seconds"),
                key="request_timeout_seconds",
                default=self.DEFAULT_REQUEST_TIMEOUT_SECONDS,
            )

        def list_tables(self) -> list[str]:
            return ["logs"]

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            self._require_known_table(table_name)
            _ = table_options
            return StructType(
                [
                    StructField("event_time", TimestampType(), False),
                    StructField("level", StringType(), True),
                    StructField("message", StringType(), True),
                    StructField("service_name", StringType(), True),
                    StructField("team", StringType(), True),
                    StructField("env", StringType(), True),
                    StructField("raw_json", StringType(), False),
                    StructField("extracted_at", TimestampType(), False),
                ]
            )

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict[str, Any]:
            self._require_known_table(table_name)
            _ = table_options
            return {
                "primary_keys": ["raw_json"],
                "cursor_field": "event_time",
                "ingestion_type": "cdc",
            }

        def read_table(
            self, table_name: str, start_offset: dict | None, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            self._require_known_table(table_name)
            options = self._parse_table_options(table_options)
            start_seconds = self._get_start_seconds(
                start_offset,
                options.initial_lookback_seconds,
                options.incremental_overlap_seconds,
            )
            if start_seconds >= self._init_end_exclusive_seconds:
                return iter([]), start_offset or self._window_offset(start_seconds)

            result = collect_windowed_records(
                start_seconds=start_seconds,
                end_exclusive_seconds=self._init_end_exclusive_seconds,
                window_seconds=options.window_seconds,
                max_concurrency=options.max_concurrency,
                max_events=options.max_events_per_sync,
                seen_fingerprints_at_cursor=set(
                    (start_offset or {}).get("seen_fingerprints_at_cursor", [])
                ),
                fetch_windows=lambda windows: self._fetch_windows(windows, options),
            )

            if result.resume_offset is not None:
                return (
                    iter(record.to_row() for record in result.records),
                    result.resume_offset,
                )

            end_offset = self._window_offset(result.next_cursor_seconds)
            if not result.records:
                return iter([]), end_offset

            return iter(record.to_row() for record in result.records), end_offset

        def _fetch_windows(
            self, windows: list[tuple[int, int]], options: TableOptions
        ) -> list[list[NormalizedLogRecord]]:
            client = TsugaPublicLogsClient(
                self._base_url,
                self._operation_api_key,
                request_timeout_seconds=float(options.request_timeout_seconds),
            )
            if options.max_concurrency == 1 or len(windows) == 1:
                return [
                    client.fetch_window(
                        from_seconds=window_start,
                        to_exclusive_seconds=window_end,
                        query=options.query,
                        page_size=options.page_size,
                        extracted_at=self._extracted_at,
                        cluster_id=options.cluster_id,
                        allow_truncated_seconds=options.allow_truncated_seconds,
                    )
                    for window_start, window_end in windows
                ]

            with ThreadPoolExecutor(max_workers=options.max_concurrency) as executor:
                return list(
                    executor.map(
                        lambda bounds: client.fetch_window(
                            from_seconds=bounds[0],
                            to_exclusive_seconds=bounds[1],
                            query=options.query,
                            page_size=options.page_size,
                            extracted_at=self._extracted_at,
                            cluster_id=options.cluster_id,
                            allow_truncated_seconds=options.allow_truncated_seconds,
                        ),
                        windows,
                    )
                )

        def _get_start_seconds(
            self,
            start_offset: dict | None,
            initial_lookback_seconds: int,
            incremental_overlap_seconds: int,
        ) -> int:
            if not start_offset or "cursor_seconds" not in start_offset:
                return max(0, self._init_end_exclusive_seconds - initial_lookback_seconds)

            cursor_seconds = int(start_offset["cursor_seconds"])
            # Already caught up within this run: don't rewind, so the next call
            # returns the same offset and the framework stops paginating.
            if cursor_seconds >= self._init_end_exclusive_seconds:
                return cursor_seconds
            # Mid-run resume after a max_events_per_sync truncation: the saved
            # fingerprints dedup the boundary second, no overlap rewind needed.
            if start_offset.get("seen_fingerprints_at_cursor"):
                return cursor_seconds
            # New run resuming from a previous run's cursor: rewind to pick up
            # late-arriving events near the old cursor.
            return max(0, cursor_seconds - incremental_overlap_seconds)

        def _parse_table_options(self, table_options: dict[str, str]) -> TableOptions:
            query = table_options.get("query") or self._default_query
            if not query:
                raise ValueError(
                    "Missing required option 'query'. Set 'default_query' on the "
                    "connection or 'query' in the table's table_configuration "
                    "(use '*' explicitly to ingest all logs)."
                )
            return TableOptions(
                query=query,
                cluster_id=table_options.get("cluster_id") or self._default_cluster_id,
                initial_lookback_seconds=self._parse_positive_int(
                    table_options.get("initial_lookback_seconds"),
                    key="initial_lookback_seconds",
                    default=self.DEFAULT_INITIAL_LOOKBACK_SECONDS,
                ),
                incremental_overlap_seconds=self._parse_non_negative_int(
                    table_options.get("incremental_overlap_seconds"),
                    key="incremental_overlap_seconds",
                    default=self.DEFAULT_INCREMENTAL_OVERLAP_SECONDS,
                ),
                window_seconds=self._parse_positive_int(
                    table_options.get("window_seconds"),
                    key="window_seconds",
                    default=self.DEFAULT_WINDOW_SECONDS,
                ),
                page_size=self._parse_positive_int(
                    table_options.get("page_size"),
                    key="page_size",
                    default=self.DEFAULT_PAGE_SIZE,
                ),
                max_concurrency=self._parse_positive_int(
                    table_options.get("max_concurrency"),
                    key="max_concurrency",
                    default=self.DEFAULT_MAX_CONCURRENCY,
                ),
                max_events_per_sync=self._parse_optional_positive_int(
                    table_options.get("max_events_per_sync"),
                    key="max_events_per_sync",
                ),
                request_timeout_seconds=self._parse_positive_int(
                    table_options.get("request_timeout_seconds"),
                    key="request_timeout_seconds",
                    default=self._default_request_timeout_seconds,
                ),
                allow_truncated_seconds=self._parse_bool(
                    table_options.get("allow_truncated_seconds"),
                    key="allow_truncated_seconds",
                    default=False,
                ),
            )

        def _require_known_table(self, table_name: str) -> None:
            if table_name not in self.list_tables():
                raise ValueError(f"Unknown table '{table_name}'. Supported tables: ['logs']")

        @staticmethod
        def _parse_bool(value: str | None, *, key: str, default: bool) -> bool:
            if value is None or value == "":
                return default
            normalized = value.strip().lower()
            if normalized in ("true", "1"):
                return True
            if normalized in ("false", "0"):
                return False
            raise ValueError(f"'{key}' must be 'true' or 'false'")

        @staticmethod
        def _parse_positive_int(value: str | None, *, key: str, default: int) -> int:
            if value is None or value == "":
                return default
            parsed = int(value)
            if parsed <= 0:
                raise ValueError(f"'{key}' must be > 0")
            return parsed

        @staticmethod
        def _parse_non_negative_int(value: str | None, *, key: str, default: int) -> int:
            if value is None or value == "":
                return default
            parsed = int(value)
            if parsed < 0:
                raise ValueError(f"'{key}' must be >= 0")
            return parsed

        @staticmethod
        def _parse_optional_positive_int(value: str | None, *, key: str) -> int | None:
            if value is None or value == "":
                return None
            parsed = int(value)
            if parsed <= 0:
                raise ValueError(f"'{key}' must be > 0 when provided")
            return parsed

        @staticmethod
        def _window_offset(next_cursor_seconds: int) -> dict[str, Any]:
            return {
                "cursor_seconds": next_cursor_seconds,
                "seen_fingerprints_at_cursor": [],
            }


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = TsugaLogsLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
